Algoritmo "calculos"

Var
        numero1, numero2, soma, sub, mult, divisao : real


Inicio
escreva("digite dois número: ")
leia(numero1, numero2)
      
soma <- numero1 + numero2
sub <- numero1 - numero2
mult <- numero1 * numero2
divisao <- numero1 / numero2
      
escreval ("A soma deu ", soma)
escreval ("A subtração deu ", sub)
escreval ("A multiplicação deu ", mult)
escreval ("A divisão deu ", divisao)
      
Fimalgoritmo