Algoritmo "Ex02"

Var
v1 : vetor[0..3] de inteiro
v2 : vetor[0..3] de inteiro
v3 : vetor[0..3] de inteiro
contador : inteiro

Inicio
para contador de 0 ate 3 faca
     escreva("Digite um numero: ")
     leia(v1[contador])
fimpara

para contador de 0 ate 3 faca
     escreva("Digite um numero: ")
     leia(v2[contador])
fimpara

para contador de 0 ate 3 faca
     v3[contador] <- v1[contador] + v2[contador]
     escreva(v3[contador])
fimpara

Fimalgoritmo